import { defineStore } from "pinia";

export const useSearchStore = defineStore("search", {
  state: () => ({
    searchText: "",
    cardList: [
      {
        id: 1,
        img: "https://picsum.photos/300/180",
        title: "超短卡片测试",
        avatar: "https://picsum.photos/64/64?random=11",
        name: "短图测试君",
        like: 321,
        tags: ["推荐", "全部", "生活分享", "热门"],
      },
      {
        id: 2,
        img: "https://picsum.photos/300/400",
        title: "夏天超显白的发色推荐",
        avatar: "https://picsum.photos/64/64?random=1",
        name: "小草莓美妆",
        like: 1234,
        tags: ["推荐", "彩妆", "全部", "才艺颜值", "变美", "生活分享"],
      },
      {
        id: 3,
        img: "https://picsum.photos/300/200",
        title: "这个图片很短",
        avatar: "https://picsum.photos/64/64?random=12",
        name: "小个子穿搭",
        like: 520,
        tags: ["推荐", "穿搭", "全部", "生活分享", "小个子", "时尚"],
      },
      {
        id: 4,
        img: "https://picsum.photos/300/800",
        title: "超长图排版测试",
        avatar: "https://picsum.photos/64/64?random=2",
        name: "穿搭小酱",
        like: 5628,
        tags: ["推荐", "穿搭", "全部", "运动户外", "时尚", "生活分享"],
      },
      {
        id: 5,
        img: "https://picsum.photos/300/350",
        title: "平价护肤好物分享",
        avatar: "https://picsum.photos/64/64?random=3",
        name: "护肤小能手",
        like: 782,
        tags: ["推荐", "彩妆", "全部", "生活分享", "护肤", "穿搭"],
      },
      {
        id: 6,
        img: "https://picsum.photos/300/220",
        title: "简约风桌面整理",
        avatar: "https://picsum.photos/64/64?random=13",
        name: "收纳小当家",
        like: 430,
        tags: ["推荐", "家居", "全部", "兴趣手工", "收纳", "生活分享"],
      },
      {
        id: 7,
        img: "https://picsum.photos/300/500",
        title: "网红甜品店打卡，颜值超高",
        avatar: "https://picsum.photos/64/64?random=4",
        name: "美食探店酱",
        like: 3211,
        tags: ["推荐", "美食", "全部", "生活分享", "探店", "热门"],
      },
      {
        id: 8,
        img: "https://picsum.photos/300/250",
        title: "可爱手机壁纸分享",
        avatar: "https://picsum.photos/64/64?random=14",
        name: "壁纸小姐姐",
        like: 1999,
        tags: ["推荐", "全部", "兴趣手工", "壁纸", "可爱风", "生活分享"],
      },
      {
        id: 9,
        img: "https://picsum.photos/300/600",
        title: "租房改造｜温馨小窝布置",
        avatar: "https://picsum.photos/64/64?random=9",
        name: "租房改造家",
        like: 7639,
        tags: ["推荐", "家居", "全部", "兴趣手工", "改造", "生活分享"],
      },
      {
        id: 10,
        img: "https://picsum.photos/300/430",
        title: "运动女孩日常穿搭",
        avatar: "https://picsum.photos/64/64?random=10",
        name: "运动少女",
        like: 1753,
        tags: ["推荐", "健身", "全部", "运动户外", "运动风", "穿搭"],
      },
      {
        id: 11,
        img: "https://picsum.photos/300/300",
        title: "热门游戏新皮肤测评",
        avatar: "https://picsum.photos/64/64?random=5",
        name: "游戏攻略君",
        like: 4215,
        tags: ["推荐", "游戏", "科技财经", "电竞", "热门", "全部"],
      },
      {
        id: 12,
        img: "https://picsum.photos/300/280",
        title: "旅行vlog｜海边日出太美了",
        avatar: "https://picsum.photos/64/64?random=6",
        name: "旅行日记",
        like: 3452,
        tags: ["推荐", "旅行", "全部", "生活分享", "风景", "热门"],
      },
      {
        id: 13,
        img: "https://picsum.photos/300/320",
        title: "职场高效时间管理技巧",
        avatar: "https://picsum.photos/64/64?random=7",
        name: "职场导师",
        like: 2431,
        tags: ["推荐", "职场", "全部", "科技财经", "干货", "生活分享"],
      },
      {
        id: 14,
        img: "https://picsum.photos/300/290",
        title: "情感治愈｜好好爱自己",
        avatar: "https://picsum.photos/64/64?random=8",
        name: "情感电台",
        like: 5321,
        tags: ["推荐", "情感", "全部", "生活分享", "治愈", "热门"],
      },
      {
        id: 15,
        img: "https://picsum.photos/300/310",
        title: "最新电影推荐合集",
        avatar: "https://picsum.photos/64/64?random=15",
        name: "影视推荐官",
        like: 6754,
        tags: ["推荐", "影视", "全部", "才艺颜值", "电影", "生活分享"],
      },
      {
        id: 16,
        img: "https://picsum.photos/300/350",
        title: "居家低脂早餐做法",
        avatar: "https://picsum.photos/64/64?random=16",
        name: "早餐小厨",
        like: 2123,
        tags: ["推荐", "美食", "全部", "生活分享", "健身", "低脂"],
      },
      {
        id: 17,
        img: "https://picsum.photos/300/420",
        title: "日常淡妆新手教程",
        avatar: "https://picsum.photos/64/64?random=17",
        name: "彩妆教程酱",
        like: 5421,
        tags: ["推荐", "彩妆", "全部", "才艺颜值", "生活分享", "变美"],
      },
      {
        id: 18,
        img: "https://picsum.photos/300/380",
        title: "春日温柔系穿搭分享",
        avatar: "https://picsum.photos/64/64?random=18",
        name: "穿搭日记",
        like: 4321,
        tags: ["推荐", "穿搭", "全部", "时尚", "生活分享", "热门"],
      },
      {
        id: 19,
        img: "https://picsum.photos/300/270",
        title: "温馨卧室布置小技巧",
        avatar: "https://picsum.photos/64/64?random=19",
        name: "家居设计师",
        like: 3278,
        tags: ["推荐", "家居", "全部", "兴趣手工", "生活分享", "改造"],
      },
      {
        id: 20,
        img: "https://picsum.photos/300/450",
        title: "30分钟燃脂健身操",
        avatar: "https://picsum.photos/64/64?random=20",
        name: "健身教练",
        like: 7521,
        tags: ["推荐", "健身", "全部", "运动户外", "健康", "生活分享"],
      },
      {
        id: 21,
        img: "https://picsum.photos/300/330",
        title: "热门手游攻略技巧",
        avatar: "https://picsum.photos/64/64?random=21",
        name: "游戏大神",
        like: 6123,
        tags: ["推荐", "游戏", "全部", "科技财经", "电竞", "热门"],
      },
      {
        id: 22,
        img: "https://picsum.photos/300/390",
        title: "城市周边小众旅行地",
        avatar: "https://picsum.photos/64/64?random=22",
        name: "旅行攻略君",
        like: 2435,
        tags: ["推荐", "旅行", "全部", "生活分享", "风景", "热门"],
      },
      {
        id: 23,
        img: "https://picsum.photos/300/260",
        title: "职场沟通高情商话术",
        avatar: "https://picsum.photos/64/64?random=23",
        name: "职场达人",
        like: 3567,
        tags: ["推荐", "职场", "全部", "科技财经", "干货", "生活分享"],
      },
      {
        id: 24,
        img: "https://picsum.photos/300/340",
        title: "情感关系维护小技巧",
        avatar: "https://picsum.photos/64/64?random=24",
        name: "情感咨询师",
        like: 4231,
        tags: ["推荐", "情感", "全部", "生活分享", "治愈", "热门"],
      },
      {
        id: 25,
        img: "https://picsum.photos/300/410",
        title: "高分冷门影视剧推荐",
        avatar: "https://picsum.photos/64/64?random=25",
        name: "影视达人",
        like: 5123,
        tags: ["推荐", "影视", "全部", "才艺颜值", "电影", "生活分享"],
      },
      {
        id: 26,
        img: "https://picsum.photos/300/280",
        title: "手工DIY可爱小摆件",
        avatar: "https://picsum.photos/64/64?random=26",
        name: "手工小匠",
        like: 2678,
        tags: ["推荐", "全部", "兴趣手工", "生活分享", "家居", "改造"],
      },
      {
        id: 27,
        img: "https://picsum.photos/300/360",
        title: "夏日清爽饮品制作",
        avatar: "https://picsum.photos/64/64?random=27",
        name: "饮品小厨",
        like: 3421,
        tags: ["推荐", "美食", "全部", "生活分享", "探店", "热门"],
      },
      {
        id: 28,
        img: "https://picsum.photos/300/320",
        title: "户外运动装备推荐",
        avatar: "https://picsum.photos/64/64?random=28",
        name: "户外达人",
        like: 2567,
        tags: ["推荐", "健身", "全部", "运动户外", "旅行", "健康"],
      },
      {
        id: 29,
        img: "https://picsum.photos/300/370",
        title: "新手化妆避坑指南",
        avatar: "https://picsum.photos/64/64?random=29",
        name: "美妆避坑酱",
        like: 4325,
        tags: ["推荐", "彩妆", "全部", "才艺颜值", "变美", "生活分享"],
      },
      {
        id: 30,
        img: "https://picsum.photos/300/400",
        title: "时尚百搭单品合集",
        avatar: "https://picsum.photos/64/64?random=30",
        name: "时尚搭配师",
        like: 5432,
        tags: ["推荐", "穿搭", "全部", "时尚", "生活分享", "热门", "视频"],
      },
    ],
    redCardList: [
      {
        id: 101,
        img: "https://picsum.photos/300/420?random=red1",
        title: "RED独家｜设计师品牌联名系列",
        avatar: "https://picsum.photos/64/64?random=r1",
        name: "RED时尚官",
        like: 8923,
        tags: ["RED精选", "时尚", "穿搭", "设计师", "限量"],
      },
      {
        id: 102,
        img: "https://picsum.photos/300/350?random=red2",
        title: "明星同款｜周也私服穿搭分享",
        avatar: "https://picsum.photos/64/64?random=r2",
        name: "明星衣橱",
        like: 12531,
        tags: ["RED精选", "明星", "穿搭", "私服", "热门"],
      },
      {
        id: 103,
        img: "https://picsum.photos/300/500?random=red3",
        title: "RED首发｜春季限定彩妆礼盒",
        avatar: "https://picsum.photos/64/64?random=r3",
        name: "RED美妆馆",
        like: 9876,
        tags: ["RED精选", "彩妆", "限定", "礼盒", "美妆"],
      },
      {
        id: 104,
        img: "https://picsum.photos/300/380?random=red4",
        title: "RED探店｜上海新晋网红咖啡店",
        avatar: "https://picsum.photos/64/64?random=r4",
        name: "城市探险家",
        like: 7623,
        tags: ["RED精选", "美食", "探店", "咖啡", "上海"],
      },
      {
        id: 105,
        img: "https://picsum.photos/300/450?random=red5",
        title: "RED好物｜年度最受欢迎护肤清单",
        avatar: "https://picsum.photos/64/64?random=r5",
        name: "成分研究所",
        like: 15321,
        tags: ["RED精选", "护肤", "清单", "年度", "热门"],
      },
      {
        id: 106,
        img: "https://picsum.photos/300/320?random=red6",
        title: "RED特辑｜春日赏花穿搭灵感",
        avatar: "https://picsum.photos/64/64?random=r6",
        name: "穿搭灵感库",
        like: 6234,
        tags: ["RED精选", "穿搭", "春季", "赏花", "灵感"],
      },
      {
        id: 107,
        img: "https://picsum.photos/300/480?random=red7",
        title: "RED独家｜小众设计师品牌推荐",
        avatar: "https://picsum.photos/64/64?random=r7",
        name: "小众品牌发掘",
        like: 8345,
        tags: ["RED精选", "时尚", "设计师", "小众", "品牌"],
      },
      {
        id: 108,
        img: "https://picsum.photos/300/360?random=red8",
        title: "RED直播｜美妆达人手把手教学",
        avatar: "https://picsum.photos/64/64?random=r8",
        name: "美妆课堂",
        like: 11234,
        tags: ["RED精选", "彩妆", "直播", "教程", "美妆"],
      },
      {
        id: 109,
        img: "https://picsum.photos/300/400?random=red9",
        title: "RED测评｜热门香水真实测评",
        avatar: "https://picsum.photos/64/64?random=r9",
        name: "香水测评师",
        like: 9456,
        tags: ["RED精选", "香水", "测评", "热门", "美妆"],
      },
      {
        id: 110,
        img: "https://picsum.photos/300/340?random=red10",
        title: "RED旅行｜小众旅行地推荐",
        avatar: "https://picsum.photos/64/64?random=r10",
        name: "旅行推荐官",
        like: 7834,
        tags: ["RED精选", "旅行", "小众", "攻略", "风景"],
      },
      {
        id: 111,
        img: "https://picsum.photos/300/460?random=red11",
        title: "RED家居｜ins风客厅改造",
        avatar: "https://picsum.photos/64/64?random=r11",
        name: "家居改造家",
        like: 6723,
        tags: ["RED精选", "家居", "改造", "ins风", "客厅"],
      },
      {
        id: 112,
        img: "https://picsum.photos/300/330?random=red12",
        title: "RED数码｜年度数码好物清单",
        avatar: "https://picsum.photos/64/64?random=r12",
        name: "数码发烧友",
        like: 8956,
        tags: ["RED精选", "数码", "清单", "科技", "年度"],
      },
    ],
    liveCardList: [
      {
        id: 201,
        img: "https://picsum.photos/300/400?random=live1",
        title: "王者荣耀｜新赛季上分攻略",
        avatar: "https://picsum.photos/64/64?random=l1",
        name: "王者小能手",
        like: 15234,
        tags: ["全部", "游戏", "王者荣耀", "直播", "攻略"],
      },
      {
        id: 202,
        img: "https://picsum.photos/300/350?random=live2",
        title: "舞蹈直播｜爵士舞基本功教学",
        avatar: "https://picsum.photos/64/64?random=l2",
        name: "舞蹈老师Lisa",
        like: 8923,
        tags: ["全部", "才艺直播", "舞蹈", "爵士舞", "教学"],
      },
      {
        id: 203,
        img: "https://picsum.photos/300/450?random=live3",
        title: "美食直播｜深夜食堂制作",
        avatar: "https://picsum.photos/64/64?random=l3",
        name: "深夜大厨",
        like: 12345,
        tags: ["全部", "生活分享", "美食", "烹饪", "深夜食堂"],
      },
      {
        id: 204,
        img: "https://picsum.photos/300/380?random=live4",
        title: "手工DIY｜奶油胶手机壳制作",
        avatar: "https://picsum.photos/64/64?random=l4",
        name: "手工小铺",
        like: 6723,
        tags: ["全部", "兴趣手工", "DIY", "奶油胶", "手工"],
      },
      {
        id: 205,
        img: "https://picsum.photos/300/420?random=live5",
        title: "股市分析｜每日大盘解读",
        avatar: "https://picsum.photos/64/64?random=l5",
        name: "财经达人",
        like: 9834,
        tags: ["全部", "科技财经", "股市", "财经", "分析"],
      },
      {
        id: 206,
        img: "https://picsum.photos/300/360?random=live6",
        title: "户外徒步｜黄山日出直播",
        avatar: "https://picsum.photos/64/64?random=l6",
        name: "户外探险家",
        like: 7523,
        tags: ["全部", "户外运动", "徒步", "旅行", "风景"],
      },
      {
        id: 207,
        img: "https://picsum.photos/300/480?random=live7",
        title: "LOL｜职业选手操作教学",
        avatar: "https://picsum.photos/64/64?random=l7",
        name: "电竞教练",
        like: 18234,
        tags: ["全部", "游戏", "LOL", "电竞", "教学"],
      },
      {
        id: 208,
        img: "https://picsum.photos/300/320?random=live8",
        title: "唱歌直播｜治愈系歌声",
        avatar: "https://picsum.photos/64/64?random=l8",
        name: "治愈歌手",
        like: 11534,
        tags: ["全部", "才艺直播", "唱歌", "音乐", "治愈"],
      },
      {
        id: 209,
        img: "https://picsum.photos/300/440?random=live9",
        title: "穿搭分享｜职场通勤穿搭",
        avatar: "https://picsum.photos/64/64?random=l9",
        name: "职场穿搭师",
        like: 8234,
        tags: ["全部", "生活分享", "穿搭", "职场", "通勤"],
      },
      {
        id: 210,
        img: "https://picsum.photos/300/390?random=live10",
        title: "绘画直播｜水彩风景画",
        avatar: "https://picsum.photos/64/64?random=l10",
        name: "水彩画家",
        like: 5623,
        tags: ["全部", "兴趣手工", "绘画", "水彩", "艺术"],
      },
      {
        id: 211,
        img: "https://picsum.photos/300/460?random=live11",
        title: "科技测评｜新款手机体验",
        avatar: "https://picsum.photos/64/64?random=l11",
        name: "科技博主",
        like: 13456,
        tags: ["全部", "科技财经", "数码", "测评", "手机"],
      },
      {
        id: 212,
        img: "https://picsum.photos/300/340?random=live12",
        title: "瑜伽直播｜晨间拉伸练习",
        avatar: "https://picsum.photos/64/64?random=l12",
        name: "瑜伽教练",
        like: 7834,
        tags: ["全部", "户外运动", "瑜伽", "健身", "健康"],
      },
      {
        id: 213,
        img: "https://picsum.photos/300/410?random=live13",
        title: "原神｜新角色攻略详解",
        avatar: "https://picsum.photos/64/64?random=l13",
        name: "原神攻略组",
        like: 16234,
        tags: ["全部", "游戏", "原神", "攻略", "角色"],
      },
      {
        id: 214,
        img: "https://picsum.photos/300/370?random=live14",
        title: "乐器演奏｜钢琴即兴表演",
        avatar: "https://picsum.photos/64/64?random=l14",
        name: "钢琴小王子",
        like: 9234,
        tags: ["全部", "才艺直播", "钢琴", "音乐", "演奏"],
      },
      {
        id: 215,
        img: "https://picsum.photos/300/430?random=live15",
        title: "烘焙直播｜巴斯克蛋糕制作",
        avatar: "https://picsum.photos/64/64?random=l15",
        name: "烘焙达人",
        like: 10534,
        tags: ["全部", "生活分享", "美食", "烘焙", "蛋糕"],
      },
      {
        id: 216,
        img: "https://picsum.photos/300/330?random=live16",
        title: "手账制作｜复古风手账教程",
        avatar: "https://picsum.photos/64/64?random=l16",
        name: "手账小达人",
        like: 6321,
        tags: ["全部", "兴趣手工", "手账", "DIY", "复古"],
      },
    ],
  }),
  activeMenu: "home",

  actions: {
    setSearchText(val) {
      this.searchText = val;
    },
    setActiveMenu(val) {
      this.activeMenu = val;
    },
  },
});
